import { marker } from '@biesbjerg/ngx-translate-extract-marker';
import { RegionWithData } from '../helpers/cities.helper';

export interface LocalizationAreaInterface {
  id: number;
  regions: RegionWithData[];
  name: string;
  name_en: string;
  img: any;
}

export const CitiesKeys: any = {
  vinnickaya_oblast: marker('Вінницька область'),
  bar: marker('Бар'),
  bersad: marker('Бершадь'),
  vinnica: marker('Вінниця'),
  gaisin: marker('Гайсин'),
  gnivan: marker('Гнівань'),
  zmerinka: marker('Жмеринка'),
  ilincy: marker('Іллінці'),
  kazatin: marker('Козятин'),
  kalinovka: marker('Калинівка'),
  kryzopol: marker('Крижопіль'),
  ladyzin: marker('Ладижин'),
  lipovec: marker('Липовець'),
  litin: marker('Літин'),
  mogilev_podolskii: marker('Могилів-Подільський'),
  murovanye_kurilovcy: marker('Муровані Курилівці'),
  nemirov: marker('Немирів'),
  oratov: marker('Оратів'),
  pescanka: marker('Піщанка'),
  pogrebishhe: marker('Погребище'),
  teplik: marker('Теплик'),
  tomaspol: marker('Томашпіль'),
  trostyanec_vinnickaya_oblast: marker('Тростянець (Вінницька область)'),
  tulcin: marker('Тульчин'),
  tyvrov: marker('Тиврів'),
  xmelnik: marker('Хмільник'),
  cecelnik: marker('Чечельник'),
  sargorod: marker('Шаргород'),
  yampol_vinnickaya_oblast: marker('Ямпіль (Вінницька область)'),
  volynskaya_oblast: marker('Волинська область'),
  berestecko: marker('Берестечко'),
  vladimir_volynskii: marker('Володимир-Волинський'),
  goroxov: marker('Горохів'),
  ivanici: marker('Іваничі'),
  kamen_kasirskii: marker('Камінь-Каширський'),
  kivercy: marker('Ківерці'),
  kovel: marker('Ковель'),
  lokaci: marker('Локачі'),
  luck: marker('Луцьк'),
  lyubesov: marker('Любешів'),
  lyuboml: marker('Любомль'),
  manevici: marker('Маневичі'),
  novovolynsk: marker('Нововолинськ'),
  ratno: marker('Ратно'),
  rozishhe: marker('Рожище'),
  staraya_vyzevka: marker('стара Вижівка'),
  ustilug: marker('Устилуг'),
  sack_volynskaya_oblast: marker('Шацьк (Волинська область)'),
  dnepropetrovskaya_oblast: marker('Дніпропетровська область'),
  apostolovo: marker('Апостолове'),
  vasilkovka: marker('Васильківка'),
  verxnedneprovsk: marker('Верхньодніпровськ'),
  verxovcevo: marker('Верхівцеве'),
  volnogorsk: marker('Вільногірськ'),
  dnepr_dnepropetrovsk: marker('Дніпро (Дніпропетровськ)'),
  kamenskoe: marker('Кам\'янське'),
  zeltye_vody: marker('Жовті Води'),
  zelenodolsk_dnepropetrovskaya_oblast: marker('Зеленодольськ (Дніпропетровська область)'),
  krivoi_rog: marker('Кривий Ріг'),
  krinicki: marker('Кринички'),
  magdalinovka: marker('Магдалинівка'),
  marganec: marker('Марганець'),
  mezevaya: marker('Межова'),
  nikopol: marker('Нікополь'),
  novomoskovsk_dnepropetrovskaya_oblast: marker('Новомосковськ (Дніпропетровська область)'),
  pavlograd: marker('Павлоград'),
  pereshhepino: marker('Перещепине'),
  persotravensk: marker('Першотравенськ'),
  petrikovka: marker('Петриківка'),
  petropavlovka: marker('Петропавлівка'),
  podgorodnoe: marker('Підгородне'),
  pokrov_dnepropetrovskaya_oblast: marker('Покров (Дніпропетровська область)'),
  pokrovskoe: marker('Покровське'),
  pyatixatki: marker('П\'ятихатки'),
  sinelnikovo: marker('Синельникове'),
  solenoe: marker('Солоне'),
  sofievka: marker('Софіївка'),
  ternovka: marker('Тернівка'),
  tomakovka: marker('Томаківка'),
  caricanka: marker('Царичанка'),
  sirokoe: marker('Широке'),
  yurevka: marker('Юр\'ївка'),
  doneckaya_oblast: marker('Донецька область'),
  avdeevka: marker('Авдіївка'),
  aleksandrovka_doneckaya_oblast: marker('Олександрівка (Донецька область)'),
  amvrosievka: marker('Амвросіївка'),
  artemovo: marker('Артемово'),
  artemovsk_ukraina: marker('Артемівськ (Україна)'),
  belickoe: marker('Білицьке'),
  belozerskoe: marker('Білозерське'),
  velikaya_novoselka: marker('Великая Новоселка'),
  volnovaxa: marker('Волноваха'),
  volodarskoe_doneckaya_oblast: marker('Володарське (Донецька область)'),
  gorlovka: marker('Горлівка'),
  debalcevo: marker('Дебальцеве'),
  dzerzinsk_doneckaya_oblast: marker('Дзержинськ (Донецька область)'),
  dimitrov: marker('Димитров'),
  dobropole: marker('Добропілля'),
  dokucaevsk: marker('Докучаєвськ'),
  doneck_ukraina: marker('Донецьк, (Україна)'),
  druzkovka: marker('Дружківка'),
  enakievo: marker('Єнакієве'),
  zugres: marker('Зугрес'),
  kirovskoe_doneckaya_oblast: marker('Кіровське (Донецька область)'),
  konstantinovka: marker('Костянтинівка'),
  kramatorsk: marker('Краматорськ'),
  krasnyi_liman: marker('червоний Лиман'),
  kuraxovo: marker('Курахово'),
  makeevka: marker('Макіївка'),
  mangus: marker('Мангуш'),
  novogrodovka: marker('Новогродівка'),
  pokrovsk_doneckaya_oblast: marker('Покровск (Донецька область)'),
  rodinskoe: marker('Родинське'),
  svetlodarsk: marker('Світлодарськ'),
  svyatogorsk: marker('Святогірськ'),
  seversk_doneckaya_oblast: marker('Сіверськ (Донецька область)'),
  selidovo: marker('Селидове'),
  slavyansk: marker('Слов\'янськ'),
  soledar: marker('Соледар'),
  starobesevo: marker('Старобешеве'),
  telmanovo: marker('Тельманове'),
  torez: marker('Торез'),
  ugledar: marker('Вугледар'),
  xarcyzsk: marker('Харцизьк'),
  saxtersk_ukraina: marker('Шахтарськ (Україна)'),
  yasinovataya: marker('Ясинувата'),
  zitomirskaya_oblast: marker('Житомирська область'),
  andrusevka: marker('Андрушівка'),
  baranovka: marker('Баранівка'),
  berdicev: marker('Бердичів'),
  brusilov: marker('Брусилів'),
  volodarsk_volynskii: marker('Володарськ-Волинський'),
  dzerzinsk_zitomirskaya_oblast: marker('Дзержинськ (Житомирська область)'),
  emilcino: marker('Ємільчине'),
  zitomir: marker('Житомир'),
  irsansk: marker('Іршанськ'),
  korosten: marker('Коростень'),
  korostysev: marker('Коростишів'),
  luginy: marker('Лугини'),
  lyubar: marker('Любар'),
  malin: marker('Малин'),
  narodici: marker('Народичі'),
  novograd_volynskii: marker('Новоград-Волинський'),
  ovruc: marker('Овруч'),
  olevsk: marker('Олевськ'),
  popelnya: marker('Попільня'),
  radomysl: marker('Радомишль'),
  romanov: marker('Романов'),
  ruzin: marker('Ружин'),
  cervonoarmeisk: marker('Червоноармійська'),
  cernyaxov: marker('Черняхів'),
  cudnov: marker('Чуднів'),
  zakarpatskaya_oblast: marker('Закарпатська область'),
  beregovo: marker('Берегово'),
  velikii_bereznyi: marker('Великий Березний'),
  vinogradov: marker('Виноградів'),
  volovec: marker('Воловець'),
  irsava: marker('Іршава'),
  mezgore_zakarpatskaya_oblast: marker('Міжгір\'я (Закарпатська область)'),
  mukacevo: marker('Мукачево'),
  perecin: marker('Перечин'),
  raxov: marker('Рахів'),
  svalyava: marker('Свалява'),
  tyacev: marker('Тячів'),
  uzgorod: marker('Ужгород'),
  xust: marker('Хуст'),
  cop: marker('Чоп'),
  zaporozskaya_oblast: marker('Запорізька область'),
  akimovka: marker('Якимівка'),
  berdyansk: marker('Бердянськ'),
  bolsaya_belozerka: marker('Велика Білозерка'),
  vasilevka: marker('Василівка'),
  veseloe: marker('Веселе'),
  volnyansk: marker('Вільнянськ'),
  gulyaipole: marker('Гуляйполе'),
  dneprorudnoe: marker('Дніпрорудне'),
  zaporoze: marker('Запоріжжя'),
  kamenka_dneprovskaya: marker('Кам\'янка-Дніпровська'),
  kirillovka: marker('Кирилівка'),
  kuibysevo: marker('Куйбишеве'),
  melitopol: marker('Мелітополь'),
  mixailovka_zaporozskaya_oblast: marker('Михайлівка (Запорізька область)'),
  mariupol: marker('Маріуполь'),
  marinka: marker('Мар\'їнка'),
  mospino: marker('Моспине'),
  molocansk: marker('Молочанськ'),
  novoazovsk: marker('Новоазовськ'),
  novonikolaevka: marker('Новомиколаївка'),
  orexov: marker('Оріхів'),
  pologi: marker('Пологи'),
  priazovskoe: marker('Приазовське'),
  primorsk_zaporozskaya_oblast: marker('Приморськ (Запорізька область)'),
  tokmak: marker('Токмак'),
  rozovka: marker('Розівка'),
  cernigovka: marker('Чернігівка'),
  energodar: marker('Енергодар'),
  ivano_frankovskaya_oblast: marker('Івано-Франківська область'),
  bogorodcany: marker('Богородчани'),
  bolexov: marker('Болехів'),
  burstyn: marker('Бурштин'),
  verxovina: marker('Верховина'),
  galic_ivano_frankovskaya_oblast: marker('Галич (Івано-Франківська область)'),
  gorodenka: marker('Городенка'),
  dolina: marker('Долина'),
  ivano_frankovsk: marker('Івано-Франківськ'),
  kalus: marker('Калуш'),
  kolomyya: marker('Коломия'),
  kosov: marker('Косів'),
  nadvornaya: marker('Надвірна'),
  pereginskoe: marker('Перегінське'),
  polyanica: marker('Поляниця'),
  rogatin: marker('Рогатин'),
  roznyatov: marker('Рожнятів'),
  snyatyn: marker('Снятин'),
  tlumac: marker('Тлумач'),
  tysmenica: marker('Тисмениця'),
  yaremce: marker('Яремче'),
  kievskaya_oblast: marker('Київська область'),
  kiev: marker('Київ'),
  barysevka: marker('Баришівка'),
  belaya_cerkov: marker('Біла Церква'),
  belogorodka: marker('Білогородка'),
  berezan: marker('Березань'),
  boguslav: marker('Богуслав'),
  borispol: marker('Бориспіль'),
  borodyanka: marker('Бородянка'),
  boyarka: marker('Боярка'),
  brovary: marker('Бровари'),
  buca: marker('Буча'),
  vasilkov: marker('Васильків'),
  visnevoe: marker('Вишневе'),
  volodarka: marker('Володарка'),
  vorzel: marker('Ворзель'),
  vysgorod: marker('Вишгород'),
  gnedin: marker('Гнідин'),
  gostomel: marker('Гостомель'),
  goshha: marker('Гоща'),
  zgurovka: marker('Згурівка'),
  ivankov: marker('Іванків'),
  irpen: marker('Ірпінь'),
  kagarlyk: marker('Кагарлик'),
  makarov_kievskaya_oblast: marker('Макарів (Київська область)'),
  mironovka: marker('Миронівка'),
  obuxov: marker('Обухів'),
  pereyaslav_xmelnickii: marker('Переяслав-Хмельницький'),
  petrovskoe: marker('Петрівське'),
  polesskoe: marker('Поліське'),
  rakitnoe_kievskaya_oblast: marker('Рокитне (Київська область)'),
  rzishhev: marker('Ржищів'),
  skvira: marker('Сквира'),
  slavutic: marker('Славутич'),
  stavishhe: marker('Ставище'),
  stoyanka: marker('Стоянка'),
  tarashha: marker('Тараща'),
  tetiev: marker('Тетіїв'),
  uzin: marker('Узин'),
  ukrainka: marker('Українка'),
  fastov: marker('Фастів'),
  cabany: marker('Чабани'),
  yagotin: marker('Яготин'),
  kirovogradskaya_oblast: marker('Кіровоградська область'),
  aleksandriya_kirovogradskaya_oblast: marker('Олександрія (Кіровоградська область)'),
  aleksandrovka_kirovogradskaya_oblast: marker('Олександрівка (Кіровоградська область)'),
  bobrinec: marker('Бобринець'),
  gaivoron: marker('Гайворон'),
  golovanevsk: marker('Голованівськ'),
  dobrovelickovka: marker('Добровеличківка'),
  dolinskaya: marker('Долинська'),
  znamenka: marker('Знам\'янка'),
  kirovograd: marker('Кіровоград'),
  kompaneevka: marker('Компаніївка'),
  malaya_viska: marker('Мала Виска'),
  novgorodka: marker('Новгородка'),
  novoarxangelsk: marker('Новоархангельськ'),
  novomirgorod: marker('Новомиргород'),
  novoukrainka: marker('Новоукраїнка'),
  olsanka: marker('Вільшанка'),
  onufrievka: marker('Онуфріївка'),
  petrovo: marker('Петрове'),
  svetlovodsk: marker('Світловодськ'),
  ulyanovka_kirovogradskaya_oblast: marker('Ульянівка (Кіровоградська область)'),
  ustinovka: marker('Устинівка'),
  luganskaya_oblast: marker('Луганська область'),
  aleksandrovsk_luganskaya_oblast: marker('Олександрівськ (Луганська область)'),
  almaznaya: marker('Алмазна'),
  alcevsk: marker('Алчевськ'),
  antracit: marker('Антрацит'),
  belovodsk: marker('Біловодськ'),
  belokurakino: marker('Білокуракине'),
  bryanka: marker('Брянка'),
  kirovsk: marker('Кіровськ'),
  krasnodon: marker('Краснодон'),
  krasnyi_luc: marker('Червоний луч'),
  kremennaya: marker('Кремінна'),
  lisicansk: marker('Лисичанськ'),
  lugansk: marker('Луганськ'),
  lutugino: marker('Лутугине'),
  markovka: marker('Марківка'),
  melovoe: marker('Мілове'),
  novoaidar: marker('Новоайдар'),
  novopskov: marker('Новопсков'),
  perevalsk: marker('Перевальск'),
  popasnaya: marker('Попасна'),
  rovenki: marker('Ровеньки'),
  rubeznoe: marker('Рубіжне'),
  svatovo: marker('Сватове'),
  sverdlovsk: marker('Свердловськ'),
  severodoneck: marker('Сєвєродонецьк'),
  slavyanoserbsk: marker('Слов\'яносербськ'),
  stanica_luganskaya: marker('Станиця Луганська'),
  starobelsk: marker('Старобільськ'),
  staxanov: marker('Стаханов (Кадіївка)'),
  scaste: marker('Щастя'),
  sneznoe: marker('Сніжне'),
  troickoe: marker('Троїцьке'),
  cervonopartizansk: marker('Червонопартизанськ'),
  lvovskaya_oblast: marker('Львівська область'),
  belz: marker('Белз'),
  bobrka: marker('Бібрка'),
  borislav: marker('Борислав'),
  brody: marker('Броди'),
  busk: marker('Буськ'),
  velikie_mosty: marker('Великі Мости'),
  vinniki: marker('Винники'),
  glinyany: marker('Глиняни'),
  gorodok_lvovskaya_oblast: marker('Городок (Львівська область)'),
  dobromil: marker('Добромиль'),
  drogobyc: marker('Дрогобич'),
  dublyany: marker('Дубляни'),
  zidacov: marker('Жидачів'),
  zolkva: marker('Жовква'),
  zolocev_lvovskaya_oblast: marker('Золочів (Львівська область)'),
  kamenka_bugskaya: marker('Кам\'янка-Бузька'),
  lvov: marker('Львів'),
  morsin: marker('Моршин'),
  mostiska: marker('Мостиська'),
  novoyavorovsk: marker('Новояворівськ'),
  peremyslyany: marker('Перемишляни'),
  pustomyty: marker('Пустомити'),
  rava_russkaya: marker('Рава-Руська'),
  radexov: marker('Радехів'),
  rozdol: marker('Розділ'),
  rudki: marker('Рудки'),
  sambor: marker('Самбір'),
  skole: marker('Сколе'),
  sokal: marker('Сокаль'),
  staryi_sambor: marker('Старий Самбір'),
  stryi: marker('Стрий'),
  truskavec: marker('Трускавець'),
  turka: marker('Турка'),
  turiisk: marker('Турійськ'),
  ugnev: marker('Угнів'),
  xyrov: marker('Хирів'),
  cervonograd: marker('Червоноград'),
  yavorov: marker('Яворів'),
  nikolaevskaya_oblast: marker('Миколаївська область'),
  arbuzinka: marker('Арбузинка'),
  bastanka: marker('Баштанка'),
  berezanka: marker('Березанка'),
  bereznegovatoe: marker('Березнегувате'),
  bratskoe: marker('Братське'),
  veselinovo: marker('Веселинове'),
  voznesensk_nikolaevskaya_oblast: marker('Вознесенськ (Миколаївська область)'),
  vradievka: marker('Врадіївка'),
  domanevka: marker('Доманівка'),
  elanec: marker('Єланець'),
  kazanka: marker('Казанка'),
  krivoe_ozero: marker('Криве Озеро'),
  nikolaev: marker('Миколаїв'),
  novaya_odessa: marker('Нова Одеса'),
  novyi_bug: marker('Новий Буг'),
  ocakov: marker('Очаків'),
  pervomaisk_ukraina: marker('Первомайськ (Україна)'),
  snigirevka: marker('Снігурівка'),
  yuznoukrainsk: marker('Южноукраїнськ'),
  odesskaya_oblast: marker('Одеська область'),
  ananev: marker('Ананьїв'),
  arciz: marker('Арциз'),
  balta: marker('Балта'),
  belgorod_dnestrovskii: marker('Білгород-Дністровський'),
  belyaevka: marker('Біляївка'),
  berezovka_odesskaya_oblast: marker('Березівка (Одеська область)'),
  bolgrad: marker('Болград'),
  velikaya_mixailovka: marker('Велика Михайлівка'),
  vilkovo: marker('Вилкове'),
  ivanovka_odesskaya_oblast: marker('Іванівка (Одеська область)'),
  izmail: marker('Ізмаїл'),
  ilicevsk: marker('Іллічівськ'),
  kiliya: marker('Кілія'),
  kodyma: marker('Кодима'),
  kominternovskoe: marker('Коминтерновское'),
  kotovsk_odesskaya_oblast: marker('Котовськ (Одеська область)'),
  krasnye_okny: marker('Красні Окни'),
  lyubasevka: marker('Любашівка'),
  ovidiopol: marker('Овідіополь'),
  odessa: marker('Одеса'),
  razdelnaya: marker('Роздільна'),
  reni: marker('Рені'),
  savran: marker('Саврань'),
  sarata: marker('Сарата'),
  tarutino: marker('Тарутине'),
  tatarbunary: marker('Татарбунари'),
  teplodar: marker('Теплодар'),
  frunzovka: marker('Фрунзівка'),
  siryaevo: marker('Ширяєве'),
  yuznyi_odesskaya_oblast: marker('Південний (Одеська область)'),
  podolsk_odesskaya_oblast: marker('Подольськ (Одеська область)'),
  poltavskaya_oblast: marker('Полтавська область'),
  velikaya_bagacka: marker('Велика Багачка'),
  gadyac: marker('Гадяч'),
  globino: marker('Глобине'),
  grebenka: marker('Гребінка'),
  dikanka: marker('Диканька'),
  zenkov: marker('Зіньків'),
  karlovka: marker('Карлівка'),
  kobelyaki: marker('Кобеляки'),
  kozelshhina: marker('Козельщина'),
  gorisnie_plavni_komsomolsk: marker('Горішні Плавні (Комсомольськ)'),
  kotelva: marker('Котельва'),
  kremencug: marker('Кременчук'),
  loxvica: marker('Лохвиця'),
  lubny: marker('Лубни'),
  masevka: marker('Машівка'),
  mirgorod: marker('Миргород'),
  novye_sanzary: marker('Нові Санжари'),
  orzica: marker('Оржиця'),
  piryatin: marker('Пирятин'),
  poltava: marker('Полтава'),
  resetilovka: marker('Решетилівка'),
  semenovka_poltavskaya_oblast: marker('Семенівка (Полтавська область)'),
  xorol: marker('Хорол'),
  cervonozavodskoe: marker('Червонозаводське'),
  cernuxi: marker('Чорнухи'),
  cutovo: marker('Чутове'),
  sisaki: marker('Шишаки'),
  rovnenskaya_oblast: marker('Рівненська область'),
  berezno: marker('Березне'),
  vladimirec: marker('Володимирець'),
  demidovka: marker('Демидівка'),
  dubno: marker('Дубно'),
  dubrovica: marker('Дубровиця'),
  zarecnoe: marker('Зарічне'),
  zdolbunov: marker('Здолбунів'),
  korec: marker('Корець'),
  kostopol: marker('Костопіль'),
  varas: marker('Вараш'),
  mlinov: marker('Млинів'),
  ostrog: marker('Острог'),
  radivilov: marker('Радивилів'),
  rovno: marker('Рівне'),
  rokitnoe: marker('Рокитне'),
  sarny: marker('Сарни'),
  sumskaya_oblast: marker('Сумська область'),
  axtyrka: marker('Охтирка'),
  belopole: marker('Білопілля'),
  buryn: marker('Буринь'),
  velikaya_pisarevka: marker('Велика Писарівка'),
  vorozba: marker('Ворожба'),
  gluxov: marker('Глухів'),
  druzba: marker('Дружба'),
  konotop: marker('Конотоп'),
  krasnopole_sumskaya_oblast: marker('Краснопілля (Сумська область)'),
  krolevec: marker('Кролевець'),
  lebedin: marker('Лебедин'),
  lipovaya_dolina: marker('Липова Долина'),
  nedrigailov: marker('Недригайлів'),
  putivl: marker('Путивль'),
  romny: marker('Ромни'),
  seredina_buda: marker('Середина-Буда'),
  sumy: marker('Суми'),
  trostyanec_sumskaya_oblast: marker('Тростянец (Сумская область)'),
  sostka: marker('Шостка'),
  yampol_sumskaya_oblast: marker('Ямпіль (Сумська область)'),
  ternopolskaya_oblast: marker('Тернопільська область'),
  berezany: marker('Бережани'),
  borshhev: marker('Борщів'),
  bucac: marker('Бучач'),
  gusyatin: marker('Гусятин'),
  zaleshhiki: marker('Заліщики'),
  zbaraz: marker('Збараж'),
  zborov: marker('Зборів'),
  kozova: marker('Козова'),
  kopycincy: marker('Копичинці'),
  kremenec: marker('Кременець'),
  lanovcy: marker('Ланівці'),
  monastyriska: marker('Монастириська'),
  podvolocisk: marker('Підволочиськ'),
  podgaicy: marker('Підгайці'),
  pocaev: marker('Почаїв'),
  skalat: marker('Скалат'),
  terebovlya: marker('Теребовля'),
  ternopol: marker('Тернопіль'),
  cortkov: marker('Чортків'),
  sumsk: marker('Шумськ'),
  xarkovskaya_oblast: marker('Харківська область'),
  balakleya: marker('Балаклія'),
  barvenkovo: marker('Барвінкове'),
  bliznyuki: marker('Близнюки'),
  bogoduxov: marker('Богодухів'),
  valki: marker('Валки'),
  velikii_burluk: marker('Великий Бурлук'),
  volcansk_xarkovskaya_oblast: marker('Вовчанськ (Харківська область)'),
  dvurecnaya: marker('Дворічна'),
  dergaci: marker('Дергачі'),
  zacepilovka: marker('Зачепилівка'),
  zmiev: marker('Зміїв'),
  zolocev_xarkovskaya_oblast: marker('Золочів (Харківська область)'),
  izyum: marker('Ізюм'),
  kegicevka: marker('Кегичівка'),
  kolomak: marker('Коломак'),
  komsomolskoe: marker('Комсомольське'),
  krasnograd: marker('Красноград'),
  krasnokutsk: marker('Краснокутськ'),
  kupyansk: marker('Куп\'янськ'),
  lozovaya: marker('Лозова'),
  lyubotin: marker('Люботин'),
  malaya_danilovka: marker('Мала Данилівка'),
  merefa: marker('Мерефа'),
  novaya_vodolaga: marker('Нова Водолага'),
  pervomaiskii_xarkovskaya_oblast: marker('Первомайський (Харківська область)'),
  pecenegi: marker('Печеніги'),
  saxnovshhina: marker('Сахновщина'),
  xarkov: marker('Харків'),
  cuguev: marker('Чугуїв'),
  sevcenkovo: marker('Шевченкове'),
  xersonskaya_oblast: marker('Херсонська область'),
  belozerka: marker('Білозерка'),
  berislav: marker('Берислав'),
  velikaya_aleksandrovka: marker('Велика Олександрівка'),
  velikaya_lepetixa: marker('Великая Лепетиха'),
  velikie_kopani: marker('Великі Копані'),
  verxnii_rogacik: marker('Верхній Рогачик'),
  vysokopole: marker('Високопілля'),
  genicesk: marker('Генічеськ'),
  golaya_pristan: marker('Гола Пристань'),
  gornostaevka: marker('Горностаївка'),
  ivanovka_xersonskaya_oblast: marker('Іванівка (Херсонська область)'),
  kalancak: marker('Каланчак'),
  kaxovka: marker('Каховка'),
  niznie_serogozy: marker('Нижні Сірогози'),
  novaya_kaxovka: marker('Нова Каховка'),
  novovoroncovka: marker('Нововоронцовка'),
  novotroickoe: marker('Новотроїцьке'),
  skadovsk: marker('Скадовськ'),
  tavriisk: marker('Таврійськ'),
  xerson: marker('Херсон'),
  cyurupinsk: marker('Цюрупинськ'),
  caplinka: marker('Чаплинка'),
  xmelnickaya_oblast: marker('Хмельницька область'),
  belogore: marker('Білогір\'я'),
  vinkovcy: marker('Віньківці'),
  volocisk: marker('Волочиськ'),
  gorodok_xmelnickaya_oblast: marker('Городок (Хмельницька область)'),
  deraznya: marker('Деражня'),
  dunaevcy: marker('Дунаївці'),
  izyaslav: marker('Ізяслав'),
  kamenec_podolskii: marker('Кам\'янець-Подільський'),
  krasilov: marker('Красилів'),
  leticev: marker('Летичів'),
  netesin: marker('Нетішин'),
  novaya_usica: marker('Нова Ушиця'),
  polonnoe: marker('Полонне'),
  slavuta: marker('Славута'),
  staraya_sinyava: marker('Стара Синява'),
  starokonstantinov: marker('Старокостянтинів'),
  teofipol: marker('Теофіполь'),
  xmelnickii: marker('Хмельницький'),
  cemerovcy: marker('Чемерівці'),
  sepetovka: marker('Шепетівка'),
  yarmolincy: marker('Ярмолинці'),
  cerkasskaya_oblast: marker('Черкаська область'),
  vatutino: marker('Ватутино'),
  gorodishhe_cerkasskaya_oblast: marker('Городище (Черкасская область)'),
  drabov: marker('Драбів'),
  zaskov: marker('Жашків'),
  zvenigorodka: marker('Звенигородка'),
  zolotonosa: marker('Золотоноша'),
  kamenka_cerkasskaya_oblast: marker('Кам\'янка (Черкаська область)'),
  kanev: marker('Канів'),
  katerinopol: marker('Катеринопіль'),
  korsun_sevcenkovskii: marker('Корсунь-Шевченківський'),
  lysyanka: marker('Лисянка'),
  mankovka: marker('Маньківка'),
  monastyrishhe: marker('Монастирище'),
  smela: marker('Сміла'),
  talnoe: marker('Тальне'),
  uman: marker('Умань'),
  xristinovka: marker('Христинівка'),
  cerkassy: marker('Черкаси'),
  cernobai: marker('Чорнобай'),
  cigirin: marker('Чигирин'),
  spola: marker('Шпола'),
  cernigovskaya_oblast: marker('Чернігівська область'),
  baxmac: marker('Бахмач'),
  bobrovica: marker('Бобровиця'),
  borzna: marker('Борзна'),
  varva: marker('Варва'),
  gorodnya: marker('Городня'),
  icnya: marker('Ічня'),
  kozelec: marker('Козелець'),
  korop: marker('Короп'),
  koryukovka: marker('Корюківка'),
  kulikovka: marker('Куликівка'),
  mena: marker('Мена'),
  nezin: marker('Ніжин'),
  novgorod_severskii: marker('Новгород-Сіверський'),
  nosovka: marker('Носівка'),
  priluki: marker('Прилуки'),
  repki: marker('Ріпки'),
  sednev: marker('Седнєв'),
  semenovka_cernigovskaya_oblast: marker('Семенівка (Чернігівська область)'),
  sosnica: marker('Сосниця'),
  srebnoe: marker('Срібне'),
  talalaevka: marker('Талалаївка'),
  cernigov: marker('Чернігів'),
  shhors: marker('Щорс'),
  cernovickaya_oblast: marker('Чернівецька область'),
  baturin: marker('Батурин'),
  vaskovcy: marker('Вашківці'),
  viznica: marker('Вижниця'),
  gerca: marker('Герца'),
  glybokaya: marker('Глибока'),
  zastavna: marker('Заставна'),
  kelmency: marker('Кельменці'),
  kicman: marker('Кіцмань'),
  novodnestrovsk: marker('Новодністровськ'),
  novoselica: marker('Новоселиця'),
  putila: marker('Путила'),
  sokiryany: marker('Сокиряни'),
  storozinec: marker('Сторожинець'),
  xotin: marker('Хотин'),
  cernovcy: marker('Чернівці'),
};

export function getLocalizationCityKey(name: string) {
  return CitiesKeys[name] ? CitiesKeys[name] : name;
}
// tslint:disable-next-line:max-file-line-count
